name: Build and Test
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.4
    - name: Build and test with Gradle
      run: ./gradlew build