name: Bump Version
on:
  push:
    tags:
      - 'v*'
jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Bump version using Git tag
      run: ./gradlew updateVersion -Pversion=${GITHUB_REF#refs/tags/}