name: Generate Codebase Diagram

on:
  push:
    branches:
      - main

jobs:
  create_diagram:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Generate diagram
      uses: githubocto/repo-visualizer@main
      with:
        output_file: "diagram.svg"
        exclusions: "**/*.test.js,**/node_modules/**"